# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.0
language: swift
xcode_project: Example/BackingStore.xcodeproj
xcode_scheme: Pods-BackigStore_Tests
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone XR
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/BackingStore.xcworkspace -scheme BackingStore-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
